blank_issues_enabled: false
contact_links:
  - name: Qinaii Labs Discord
    url: https://discord.gg/UDyN94HSGx
    about: Community chat and general questions
  - name: qinaii.de
    url: https://qinaii.de
    about: More Qinaii Labs projects
